using UnityEngine;

/// <summary>
/// Helpers for helper objects generated by converters. These are not saved with the scene,
/// they only exist so they can be converted into slots.
/// </summary>
public static class GeneratedObjectHelper
{
    public static bool IsGenerated(Transform transform) => (transform.gameObject.hideFlags & HideFlags.DontSave) != 0;

    /// <summary>
    /// Finds or creates a generated child object with given name
    /// </summary>
    public static GameObject EnsureChild(Transform parent, string name)
    {
        for (int i = 0; i < parent.childCount; i++)
        {
            var child = parent.GetChild(i);

            if (child.name == name && IsGenerated(child))
                return child.gameObject;
        }

        return Create(parent, name);
    }

    public static GameObject Create(Transform parent, string name)
    {
        var obj = new GameObject(name);
        obj.hideFlags = HideFlags.DontSave;
        obj.transform.SetParent(parent, false);

        return obj;
    }

    public static T EnsureComponent<T>(GameObject obj) where T : Component
    {
        var component = obj.GetComponent<T>();

        if (component == null)
            component = obj.AddComponent<T>();

        return component;
    }

    public static void Destroy(ref GameObject obj)
    {
        if (obj != null)
            Object.DestroyImmediate(obj);

        obj = null;
    }
}
