using UnityEngine;

/// <summary>
/// Helpers for helper objects generated by converters. These are not saved with the scene,
/// they only exist so they can be converted into slots.
/// </summary>
public static class GeneratedObjectHelper
{
    public static bool IsGenerated(Transform transform) => (transform.gameObject.hideFlags & HideFlags.DontSave) != 0;

    /// <summary>
    /// Finds or creates a generated child object with given name
    /// </summary>
    public static GameObject EnsureChild(Transform parent, string name)
    {
        for (int i = 0; i < parent.childCount; i++)
        {
            var child = parent.GetChild(i);

            if (child.name == name && IsGenerated(child))
                return child.gameObject;
        }

        return Create(parent, name);
    }

    public static GameObject Create(Transform parent, string name)
    {
        var obj = new GameObject(name);
        obj.hideFlags = HideFlags.DontSave;
        obj.transform.SetParent(parent, false);

        return obj;
    }

    /// <summary>
    /// Only assigns the values when they changed, so we don't generate needless change events in realtime mode
    /// </summary>
    public static void SetLocalPose(Transform transform, Vector3 position, Quaternion rotation)
    {
        if (transform.localPosition != position)
            transform.localPosition = position;

        if (transform.localRotation != rotation)
            transform.localRotation = rotation;
    }

    public static void Destroy(ref GameObject obj)
    {
        if (obj != null)
            Object.DestroyImmediate(obj);

        obj = null;
    }

    /// <summary>
    /// Destroys the generated object and any generated parents that are left empty after that
    /// (e.g. shared menu containers)
    /// </summary>
    public static void DestroyWithEmptyParents(ref GameObject obj)
    {
        var parent = obj != null ? obj.transform.parent : null;

        Destroy(ref obj);

        while (parent != null && IsGenerated(parent) && parent.childCount == 0)
        {
            var next = parent.parent;
            Object.DestroyImmediate(parent.gameObject);
            parent = next;
        }
    }
}
